// Global Image Constants - Cloudinary Optimized URLs
// Auto-generated by upload-constants.js on 2026-01-23T11:23:09.841Z

export const SCPC_LOGO_URL = "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/scpc?_a=BAMAOGRg0";

// Team member images (Cloudinary optimized)
export const TEAM_IMAGES = {
  AAYUSH: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/aayush_new?_a=BAMAOGRg0",
  AYUSH: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/ayush_new?_a=BAMAOGRg0",
  CHETAN: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/chetan_new?_a=BAMAOGRg0",
  CORE: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/core_new?_a=BAMAOGRg0",
  KANCHAN: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kanchan_new?_a=BAMAOGRg0",
  KASHISH: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kashish_new?_a=BAMAOGRg0",
  KSHTIJ: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kshtij_new?_a=BAMAOGRg0",
  PRAGNESH: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/Pragnesh_new?_a=BAMAOGRg0",
  PRANJAL: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/pranjal_new?_a=BAMAOGRg0",
  PURVA: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/purva_new?_a=BAMAOGRg0",
  ROHAN: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/rohan_new?_a=BAMAOGRg0",
  RUDRA: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/rudra_new?_a=BAMAOGRg0",
  SHIVAM: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/shivam_new?_a=BAMAOGRg0",
  SHREYANSH: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/shreyansh_new?_a=BAMAOGRg0",
  SWAMINI: "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/swamini_new?_a=BAMAOGRg0",
} as const;

// Name to image URL mapping for TeamTree component
export const MEMBER_IMAGE_URLS: Record<string, string> = {
  "Aayush Dubey": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/aayush_new?_a=BAMAOGRg0",
  "Swamini Yesade": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/swamini_new?_a=BAMAOGRg0",
  "Chetan Sharma": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/chetan_new?_a=BAMAOGRg0",
  "Ayush Dubey": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/ayush_new?_a=BAMAOGRg0",
  "Pranjal Chavan": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/pranjal_new?_a=BAMAOGRg0",
  "Rudra Sharma": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/rudra_new?_a=BAMAOGRg0",
  "Kanchan Saini": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kanchan_new?_a=BAMAOGRg0",
  "Kshitij Yadav": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kshtij_new?_a=BAMAOGRg0",
  "Shreyansh Singh": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/shreyansh_new?_a=BAMAOGRg0",
  "Purva Gade": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/purva_new?_a=BAMAOGRg0",
  "Shivam Pandey": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/shivam_new?_a=BAMAOGRg0",
  "Pragnesh Dubey": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/Pragnesh_new?_a=BAMAOGRg0",
  "Rohan Dol": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/rohan_new?_a=BAMAOGRg0",
  "Kashish": "https://res.cloudinary.com/divj3y2cp/image/upload/c_fill,f_auto,g_face,h_400,q_auto,w_400/v1/scpc-team/kashish_new?_a=BAMAOGRg0",
  "Amitabh Dwivedi": "",
  "Adnan Qureshi": "",
};
